Repository fastai/fastpages, pull requests merged in 2020-02, with the labels that each got.

#105 Added excludes for internal fastpages in _config.yml
  _config.yml
Labels: bug

#108 Enable Search With lunr.js
  _config.yml
  assets/js/search.js
  assets/js/vendor/lunr.min.js
  assets/main.scss
  index.md
  search.html
Labels: enhancement

#106 docker-compose local dev env with live reload
  .gitignore
  CONTRIBUTING.md
  Gemfile.lock
  README.md
  _action_files/Dockerfile
  _dev_tools/Makefile
  _dev_tools/README.md
  _dev_tools/convert-docker-compose.yaml
  _dev_tools/docker-compose.yaml
  docker-compose.yml
Labels: enhancement

#124 Bump nokogiri re: security alert
  Gemfile.lock
Labels: upgrade-dependency

#132 Update settings.ini to fix local images when not using a root url
  _action_files/settings.ini
Labels: bug
